// dynamics.cpp -- the paper's dynamics rules for the three runtimes
// (eager, lazy arguments, lazy passes), as a standalone batch tool.
//
// THE RULES (mirror of the paper statement).  Values are the strings.
// On closed expressions, per mode, a rewrite relation generated by
// axiom schemes closed under the mode's evaluation contexts:
//   shared:   (cat)  C(K w1,K w2) -> K(w1 w2)
//             (fire) S(K wA,K wP,K wS) -> K(sub)  if wP!=eps, wP in wS
//   eager, lazy args:
//             (inert-S) S(K wA,K wP,K wS) -> K wS  if wP!=eps, wP not
//             in wS                 [strict: all three slots values]
//   lazy passes:
//             (inert-D) S(R,K wP,K wS) -> K wS  if wP!=eps, wP not in
//             wS                    [R arbitrary -- the discard]
//   eager:    (call-v) F(g,K w1..K wm) -> body_g[V i := K wi]
//   la, lp:   (call-n) F(g,E1..Em) -> body_g[V i := Ei]
//   contexts -- eager: any child of cat, any slot of the pass, any
//   call argument; lazy args: any child of cat, any slot of the pass;
//   lazy passes: any child of cat, pattern and scrutinee slots of the
//   pass, and the replacement slot ONLY under the guard: pattern and
//   scrutinee values, pattern nonempty and occurring.
//
// Batch input (one test per line on stdin):
//   mode | name:arity:sexpr,name:arity:sexpr,... | main-sexpr | in1,in2
// Output: one line per test: "val <w>" or "und".
//
// Guards: step cap 2,000,000; tree depth 100,000; 4M total chars /
// 4M nodes -- exceeding any of them classifies as "und" (aligned with
// the reference machines' fuel/budget/size caps; halting runs of the
// cross-check corpus are far below all of them).
//
// Build: g++ -O2 -std=c++17 -o dynamics_bin dynamics.cpp -lpthread

#include <pthread.h>
#include <functional>
#include <pthread.h>

#include <cstdint>
#include <cstdio>
#include <functional>
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

namespace {

// ------------------------------------------------------------- exceptions
struct DeepEx {};
struct SizeEx {};
struct ParseEx {
    std::string msg;
    explicit ParseEx(std::string m) : msg(std::move(m)) {}
};

// ----------------------------------------------------------------- nodes
struct Node;
using P = std::shared_ptr<Node>;

int64_t g_nodes = 0;
int64_t g_visits = 0;
const int64_t NODE_CAP = 4'000'000;
const int64_t CHAR_CAP = 4'000'000;
const int64_t DEPTH_CAP = 100'000;
const int64_t STEP_CAP = 2'000'000;
// Total node-visits across all step() calls: the redex search
// descends from the root each step, so growth-type divergences cost
// O(depth) per step; the work cap cuts them in bounded time.  Halting
// runs of the cross-check corpus take < 10^5 visits.
const int64_t WORK_CAP = 10'000'000;

struct Node {
    char tag;  // 'K','V','C','S','F'
    std::string w;            // K
    int vi = 0;               // V
    std::string fn;           // F
    std::vector<P> ch;        // C: 2; S: 3 (R,P,E); F: args
    explicit Node(char t) : tag(t) {
        if (++g_nodes > NODE_CAP) throw SizeEx();
    }
};

P mkK(const std::string& w) {
    auto n = std::make_shared<Node>('K');
    n->w = w;
    return n;
}
P mkV(int i) {
    auto n = std::make_shared<Node>('V');
    n->vi = i;
    return n;
}
P mkC(P a, P b) {
    auto n = std::make_shared<Node>('C');
    n->ch = {std::move(a), std::move(b)};
    return n;
}
P mkS(P r, P p, P e) {
    auto n = std::make_shared<Node>('S');
    n->ch = {std::move(r), std::move(p), std::move(e)};
    return n;
}
P mkF(const std::string& name, std::vector<P> args) {
    auto n = std::make_shared<Node>('F');
    n->fn = name;
    n->ch = std::move(args);
    return n;
}

// ------------------------------------------------------------ the pass
std::string sub_val(const std::string& A, const std::string& B,
                    const std::string& C) {
    std::string out;
    size_t i = 0, m = B.size();
    while (i < C.size()) {
        if (m && C.compare(i, m, B) == 0) {
            out += A;
            i += m;
        } else {
            out += C[i];
            i++;
        }
    }
    if ((int64_t)out.size() > CHAR_CAP) throw SizeEx();
    return out;
}

// ------------------------------------------------- expression substitution
P subst_expr(const P& E, const std::vector<P>& Fs) {
    if (++g_visits > WORK_CAP) throw SizeEx();
    switch (E->tag) {
        case 'K': return E;
        case 'V':
            if ((size_t)E->vi >= Fs.size()) throw ParseEx("var oob");
            return Fs[E->vi];
        case 'C':
            return mkC(subst_expr(E->ch[0], Fs),
                       subst_expr(E->ch[1], Fs));
        case 'S':
            return mkS(subst_expr(E->ch[0], Fs), subst_expr(E->ch[1], Fs),
                       subst_expr(E->ch[2], Fs));
        case 'F': {
            std::vector<P> a;
            a.reserve(E->ch.size());
            for (auto& x : E->ch) a.push_back(subst_expr(x, Fs));
            return mkF(E->fn, std::move(a));
        }
    }
    return nullptr;
}

std::string show(const P& E) {
    switch (E->tag) {
        case 'K': return "(K " + (E->w.empty() ? "#" : E->w) + ")";
        case 'V': return "(V " + std::to_string(E->vi) + ")";
        case 'C': return "(C " + show(E->ch[0]) + " " + show(E->ch[1]) + ")";
        case 'S': return "(S " + show(E->ch[0]) + " " + show(E->ch[1]) + " "
                         + show(E->ch[2]) + ")";
        case 'F': { std::string s = "(F " + E->fn; for (auto& x : E->ch)
                         s += " " + show(x); return s + ")"; }
    }
    return "?";
}

// ---------------------------------------------------------------- defs
struct Defs {
    std::unordered_map<std::string, std::pair<int, P>> d;  // name -> (ar, body)
};

enum Mode { EAGER, LA, LP };

// ------------------------------------------------------------------ step
P step(const P& E, Mode mode, const Defs& defs, int depth) {
    if (depth > DEPTH_CAP) throw DeepEx();
    if (++g_visits > WORK_CAP) throw SizeEx();
    switch (E->tag) {
        case 'K':
            return nullptr;
        case 'C': {
            P a = step(E->ch[0], mode, defs, depth + 1);
            if (a) return mkC(a, E->ch[1]);
            P b = step(E->ch[1], mode, defs, depth + 1);
            if (b) return mkC(E->ch[0], b);
            if (E->ch[0]->tag == 'K' && E->ch[1]->tag == 'K') {
                return mkK(E->ch[0]->w + E->ch[1]->w);          // (cat)
            }
            return nullptr;  // strict in both
        }
        case 'S': {
            const P& R = E->ch[0];
            const P& Pt = E->ch[1];
            const P& Es = E->ch[2];
            if (mode == LP) {
                P p = step(Pt, mode, defs, depth + 1);   // pattern forced
                if (p) return mkS(R, p, Es);
                P s = step(Es, mode, defs, depth + 1);   // scrutinee forced
                if (s) return mkS(R, Pt, s);
                if (Pt->tag == 'K' && Es->tag == 'K') {
                    const std::string& wP = Pt->w;
                    const std::string& wS = Es->w;
                    if (wP.empty()) return nullptr;      // [A/eps] stuck
                    if (wS.find(wP) == std::string::npos)
                        return Es;                        // (inert-D)
                    P r = step(R, mode, defs, depth + 1);  // guarded ctx
                    if (r) return mkS(r, Pt, Es);
                    if (R->tag == 'K')
                        return mkK(sub_val(R->w, wP, wS));  // (fire)
                    return nullptr;                       // R stuck
                }
                return nullptr;
            }
            // eager and lazy args: strict in all three slots
            P r = step(R, mode, defs, depth + 1);
            if (r) return mkS(r, Pt, Es);
            P p = step(Pt, mode, defs, depth + 1);
            if (p) return mkS(R, p, Es);
            P s = step(Es, mode, defs, depth + 1);
            if (s) return mkS(R, Pt, s);
            if (R->tag == 'K' && Pt->tag == 'K' && Es->tag == 'K') {
                if (Pt->w.empty()) return nullptr;
                if (Es->w.find(Pt->w) == std::string::npos)
                    return Es;                            // (inert-S)
                return mkK(sub_val(R->w, Pt->w, Es->w));  // (fire)
            }
            return nullptr;
        }
        case 'F': {
            const std::string& name = E->fn;
            if (mode == EAGER) {
                for (size_t i = 0; i < E->ch.size(); i++) {  // arg contexts
                    P sa = step(E->ch[i], mode, defs, depth + 1);
                    if (sa) {
                        std::vector<P> a = E->ch;
                        a[i] = sa;
                        return mkF(name, std::move(a));
                    }
                }
                bool allK = true;
                for (auto& x : E->ch)
                    if (x->tag != 'K') { allK = false; break; }
                if (allK) {                                 // (call-v)
                    auto it = defs.d.find(name);
                    if (it == defs.d.end()) return nullptr;
                    return subst_expr(it->second.second, E->ch);
                }
                return nullptr;                             // arg stuck
            }
            auto it = defs.d.find(name);                    // (call-n)
            if (it == defs.d.end()) return nullptr;
            return subst_expr(it->second.second, E->ch);
        }
        case 'V':
            return nullptr;  // free variable in a closed run: stuck
    }
    return nullptr;
}

std::string show(const P& E);

// ------------------------------------------------------------------ run
// Returns ("val", w) or ("und", "").
std::pair<std::string, std::string> run(const Defs& defs, const P& main,
                                        const std::vector<std::string>& inputs,
                                        Mode mode) {
    std::vector<P> Fs;
    Fs.reserve(inputs.size());
    for (auto& w : inputs) Fs.push_back(mkK(w));
    P E = subst_expr(main, Fs);
    int64_t dbg = getenv("DYN_DBG") ? atoll(getenv("DYN_DBG")) : -1;
    for (int64_t k = 0; k < STEP_CAP; k++) {
        if (k <= dbg) fprintf(stderr, "[%lld] %s\n", (long long)k, show(E).c_str());
        if (E->tag == 'K') return {"val", E->w};
        P E2;
        try {
            E2 = step(E, mode, defs, 0);
        } catch (DeepEx&) {
            return {"und", "!deep"};
        } catch (SizeEx&) {
            return {"und", "!size"};
        }
        if (!E2) return {"und", "!stuck"};  // stuck
        E = std::move(E2);
    }
    return {"und", "!stepcap"};
}

// ------------------------------------------------------------ s-expr parse
struct Tok {
    std::vector<std::string> toks;
    size_t p = 0;
    explicit Tok(const std::string& s) {
        std::string cur;
        for (char c : s) {
            if (c == '(' || c == ')') {
                if (!cur.empty()) { toks.push_back(cur); cur.clear(); }
                toks.push_back(std::string(1, c));
            } else if (c == ' ') {
                if (!cur.empty()) { toks.push_back(cur); cur.clear(); }
            } else {
                cur += c;
            }
        }
        if (!cur.empty()) toks.push_back(cur);
    }
    const std::string& peek() {
        if (p >= toks.size()) throw ParseEx("eof");
        return toks[p];
    }
    std::string pop() {
        if (p >= toks.size()) throw ParseEx("eof");
        return toks[p++];
    }
};

P parse(Tok& t) {
    if (t.pop() != "(") throw ParseEx("expected (");
    std::string h = t.pop();
    P n;
    if (h == "K") {
        std::string s = t.pop();
        if (s == "#") s = "";   // '#' encodes the empty string
        n = mkK(s);
    } else if (h == "V") {
        n = mkV(atoi(t.pop().c_str()));
    } else if (h == "C") {
        P a = parse(t), b = parse(t);
        n = mkC(a, b);
    } else if (h == "S") {
        P a = parse(t), b = parse(t), c = parse(t);
        n = mkS(a, b, c);
    } else if (h == "F") {
        std::string name = t.pop();
        std::vector<P> args;
        while (t.peek() != ")") args.push_back(parse(t));
        n = mkF(name, std::move(args));
    } else {
        throw ParseEx("bad head " + h);
    }
    if (t.pop() != ")") throw ParseEx("expected )");
    return n;
}

P parse_sexpr(const std::string& s) {
    Tok t(s);
    return parse(t);
}

std::string trim(const std::string& s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    if (a == std::string::npos) return "";
    size_t b = s.find_last_not_of(" \t\r\n");
    return s.substr(a, b - a + 1);
}

std::vector<std::string> split(const std::string& s, char sep) {
    std::vector<std::string> out;
    std::string cur;
    for (char c : s) {
        if (c == sep) { out.push_back(trim(cur)); cur.clear(); }
        else cur += c;
    }
    out.push_back(trim(cur));
    return out;
}

std::function<void()> g_work;

void* g_trampoline(void*) {
    g_work();
    return nullptr;
}

}  // namespace

int main() {
    std::string line;
    std::vector<std::string> out;
    auto work = [&]() {
        while (std::getline(std::cin, line)) {
            if (line.empty()) continue;
            try {
                g_nodes = 0;   // reset BEFORE any parsing of this test
                g_visits = 0;
                auto parts = split(line, '|');
                if (parts.size() != 4) { out.push_back("und"); continue; }
                std::string& mods = parts[0];
                Mode mode = mods == "eager" ? EAGER
                                             : (mods == "la" ? LA : LP);
                Defs defs;
                for (auto& d : split(parts[1], ',')) {
                    if (d.empty()) continue;
                    auto f = split(d, ':');
                    // f[0]=name f[1]=arity f[2]=sexpr (sexpr may contain
                    // ':'? no -- only K strings over {a,b} and digits)
                    defs.d[f[0]] = {atoi(f[1].c_str()), parse_sexpr(f[2])};
                }
                P main = parse_sexpr(parts[2]);
                std::vector<std::string> inputs = split(parts[3], ',');
                auto r = run(defs, main, inputs, mode);
                out.push_back(r.first == "val" ? "val " + r.second
 : (r.second.empty() ? "und" : "und " + r.second));
            } catch (...) {
                out.push_back("und");
            }
        }
    };
    // Deep recursion is bounded by DEPTH_CAP=100k frames; run on a
    // pthread with a 1GB stack (virtual) so it never overflows.
    g_work = work;
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, 1ull << 30);
    pthread_t tid;
    if (pthread_create(&tid, &attr, g_trampoline, nullptr) != 0) {
        work();  // fallback: run inline
    } else {
        pthread_join(tid, nullptr);
    }
    std::string res;
    for (auto& s : out) { res += s; res += '\n'; }
    fwrite(res.data(), 1, res.size(), stdout);
    return 0;
}
