/* crux_search.c — bounded search for the ONCE crux oracle on marked texts.
 *
 * Question: is [babba/baa]_1 (replace the leftmost mark `baa` by `babba`)
 * implementable by a SHALLOW pipeline of constant passes, on the marked
 * language  (cells {ba,bb} + marks {baa})*  ?
 *
 * Search space: pipelines of at most MAXD passes; each pass [R/P] with
 * P in {a,b}^{1..2} and R in {a,b}^{<=2} (R != P) — 36 pass types; this is
 * the same class that contains the paper's depth-5 witness W for [a/b]_1.
 * A DFS records any pipeline whose action on the 4-text battery equals the
 * oracle, then re-verifies survivors on 64 and then 10000 random marked
 * texts (generated by the Theorem-A pipeline: enc2, then mark all greedy
 * disjoint occurrences of enc2(Y)).
 *
 * Sound early-abort inside pass application: partial output never shrinks,
 * and each remaining input character emits at most 2 output characters, so
 *   partial > tgtlen  or  partial + 2*remaining < tgtlen  =>  abort.
 * Sound depth prune: with r = maxd-depth passes still to apply (including
 * the candidate pass), length can at most double r times, so
 *   len * 2^r < tgtlen  =>  branch cut.
 *
 * Compile: gcc -O2 -o crux_search crux_search.c
 * Run:     ./crux_search [maxdepth]
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#define MAXD 7
#define MAXS 1024
#define NB 4

static const char *PATS[6] = {"a", "b", "aa", "ab", "ba", "bb"};
static const char *REPS[7] = {"", "a", "b", "aa", "ab", "ba", "bb"};
#define NPASS 36

/* battery: marked texts (from the Theorem-A pipeline) and oracle outputs */
static const char *BAT_IN_D[NB] = {
    "baabbba",       /* Y=ab  Z=abba: mark at cell 0            */
    "babbbaa",       /* Y=ba  Z=abba: mark at the last cells    */
    "babaababaa",    /* Y=b   Z=abab: two marks with an a-gap   */
    "babb",          /* Y=aab Z=ab:   no mark (identity case)   */
};
static const char *BAT_TGT_D[NB] = {
    "babbabbba",
    "babbbabba",
    "bababbababaa",
    "babb",
};
static char bat_in_st[NB][MAXS], bat_tgt_st[NB][MAXS];
static const char *BAT_IN[NB], *BAT_TGT[NB];

static char passR[NPASS][4], passP[NPASS][4];
static int passRl[NPASS], passPl[NPASS];

/* apply pass (R,P) to in; if tgt >= 0 use sound early aborts vs tgtlen.
 * returns 0 on abort, 1 on success (out filled). */
static int apply(const int pi, const char *in, char *out, const int tgtlen)
{
    const char *R = passR[pi], *P = passP[pi];
    const int lr = passRl[pi], lp = passPl[pi];
    int i = 0, o = 0, n = (int)strlen(in);
    while (i < n) {
        if (i + lp <= n && !memcmp(in + i, P, (size_t)lp)) {
            if (tgtlen >= 0) {
                if (o + lr > tgtlen) return 0;
                if (o + lr + 2 * (n - i - lp) < tgtlen) return 0;
            }
            memcpy(out + o, R, (size_t)lr);
            o += lr;
            i += lp;
        } else {
            if (tgtlen >= 0) {
                if (o + 1 > tgtlen) return 0;
                if (o + 1 + 2 * (n - i - 1) < tgtlen) return 0;
            }
            out[o++] = in[i++];
        }
    }
    out[o] = 0;
    return 1;
}

static char cur[NB][MAXS];
static int path[MAXD];
static long long nodes = 0, found = 0;

static void report(int depth)
{
    int i;
    printf("CANDIDATE depth %d:", depth);
    for (i = 0; i < depth; i++)
        printf(" [%s/%s]", passR[path[i]], passP[path[i]]);
    printf("\n");
    fflush(stdout);
}

/* ---- marked-text machinery for verification ---- */
static unsigned int rngstate = 12345u;
static unsigned int xr(void)
{
    rngstate ^= rngstate << 13;
    rngstate ^= rngstate >> 17;
    rngstate ^= rngstate << 5;
    return rngstate;
}

static void enc2(const char *s, char *out)
{
    int o = 0;
    for (; *s; s++) {
        out[o++] = 'b';
        out[o++] = *s;
    }
    out[o] = 0;
}

static void mark(const char *T, const char *N, const char *M, char *out)
{
    int i = 0, o = 0, n = (int)strlen(T), ln = (int)strlen(N), lm = (int)strlen(M);
    while (i < n) {
        if (i + ln <= n && !memcmp(T + i, N, (size_t)ln)) {
            memcpy(out + o, M, (size_t)lm);
            o += lm;
            i += ln;
        } else
            out[o++] = T[i++];
    }
    out[o] = 0;
}

static void oracle(const char *T, char *out)
{
    const char *p = strstr(T, "baa");
    if (!p) { strcpy(out, T); return; }
    memcpy(out, T, (size_t)(p - T));
    int o = (int)(p - T);
    memcpy(out + o, "babba", 5);
    o += 5;
    strcpy(out + o, p + 3);
}

static int run_pipe(int *pp, int d, const char *in, char *tmp, char *out)
{
    char *a = out, *b = tmp;
    strcpy(a, in);
    for (int k = 0; k < d; k++) {
        if (!apply(pp[k], a, b, -1)) return 0; /* never aborts with tgt<0 */
        char *sw = a; a = b; b = sw;
    }
    if (a != out) strcpy(out, a);
    return 1;
}

static int g_mode_w = 0; /* 1: verify against [a/b]_1 on plain texts */

static int verify_candidate(int depth)
{
    /* stage 1: 64 random; stage 2: 10000 random */
    static char Z[16], Y[16], E[2 * MAXS], T[MAXS], TG[MAXS], tmp[MAXS], out[MAXS];
    long long lim[2] = {64, 10000};
    for (int st = 0; st < 2; st++) {
        rngstate = 999u + 77u * (unsigned)st;
        for (long long t = 0; t < lim[st]; t++) {
            if (g_mode_w) {
                int lz = (int)(xr() % 11);
                for (int i = 0; i < lz; i++) T[i] = (xr() & 1) ? 'a' : 'b';
                T[lz] = 0;
                const char *q = strchr(T, 'b');
                if (q) {
                    memcpy(TG, T, (size_t)(q - T));
                    TG[q - T] = 'a';
                    strcpy(TG + (q - T) + 1, q + 1);
                } else
                    strcpy(TG, T);
            } else {
                int lz = (int)(xr() % 9), ly = 1 + (int)(xr() % 3);
                for (int i = 0; i < lz; i++) Z[i] = (xr() & 1) ? 'a' : 'b';
                Z[lz] = 0;
                for (int i = 0; i < ly; i++) Y[i] = (xr() & 1) ? 'a' : 'b';
                Y[ly] = 0;
                enc2(Z, E);
                char NY[2 * 16];
                enc2(Y, NY);
                mark(E, NY, "baa", T);
                oracle(T, TG);
            }
            run_pipe(path, depth, T, tmp, out);
            if (strcmp(out, TG) != 0) return 0;
        }
    }
    return 1;
}

static void dfs(int depth, int maxd)
{
    int i, j;
    for (j = 0; j < NB; j++)
        if (strcmp(cur[j], BAT_TGT[j]) != 0) break;
    if (j == NB) { /* all texts already at target */
        found++;
        report(depth);
        if (verify_candidate(depth))
            printf(g_mode_w
                       ? "  *** VERIFIED ON 10064 RANDOM PLAIN TEXTS ***\n"
                       : "  *** VERIFIED ON 10064 RANDOM MARKED TEXTS ***\n");
        else
            printf("  (failed extended verification)\n");
        return; /* deeper pipelines along this branch are redundant */
    }
    if (depth == maxd) return;
    for (i = 0; i < NPASS; i++) {
        char nxt[NB][MAXS];
        int ok = 1;
        for (j = 0; j < NB && ok; j++) {
            int tl = (int)strlen(BAT_TGT[j]);
            if (depth + 1 == maxd) {
                ok = apply(i, cur[j], nxt[j], tl);
                if (ok) ok = !strcmp(nxt[j], BAT_TGT[j]);
            } else {
                /* depth prune: the remaining maxd-depth passes (including
                 * the one being applied now) can at most double the length
                 * each, so cut iff len * 2^(maxd-depth) < tgtlen */
                int k = maxd - depth;
                if ((long long)strlen(cur[j]) * (1 << k) < (long long)strlen(BAT_TGT[j])) {
                    ok = 0; break;
                }
                ok = apply(i, cur[j], nxt[j], -1);
            }
        }
        if (!ok) continue;
        path[depth] = i;
        char save[NB][MAXS];
        for (j = 0; j < NB; j++) strcpy(save[j], cur[j]);
        for (j = 0; j < NB; j++) strcpy(cur[j], nxt[j]);
        nodes++;
        dfs(depth + 1, maxd);
        for (j = 0; j < NB; j++) strcpy(cur[j], save[j]);
    }
}

int main(int argc, char **argv)
{
    int maxd = (argc > 1) ? atoi(argv[1]) : MAXD;
    if (maxd > MAXD) maxd = MAXD;
    if (argc > 2) { /* battery file: 4 lines inputs, 4 lines targets */
        FILE *f = fopen(argv[2], "r");
        if (!f) { perror(argv[2]); return 2; }
        for (int j = 0; j < NB; j++)
            if (!fgets(bat_in_st[j], MAXS, f)) { fprintf(stderr, "bad battery\n"); return 2; }
        for (int j = 0; j < NB; j++) {
            if (!fgets(bat_tgt_st[j], MAXS, f)) { fprintf(stderr, "bad battery\n"); return 2; }
            char *nl = strpbrk(bat_in_st[j], "\r\n"); if (nl) *nl = 0;
            nl = strpbrk(bat_tgt_st[j], "\r\n"); if (nl) *nl = 0;
            BAT_IN[j] = bat_in_st[j];
            BAT_TGT[j] = bat_tgt_st[j];
        }
        fclose(f);
    } else {
        for (int j = 0; j < NB; j++) { BAT_IN[j] = BAT_IN_D[j]; BAT_TGT[j] = BAT_TGT_D[j]; }
    }
    g_mode_w = (argc > 3);
    int pi = 0;
    for (int a = 0; a < 7; a++)
        for (int b = 0; b < 6; b++)
            if (strcmp(REPS[a], PATS[b])) {
                strcpy(passR[pi], REPS[a]);
                strcpy(passP[pi], PATS[b]);
                passRl[pi] = (int)strlen(REPS[a]);
                passPl[pi] = (int)strlen(PATS[b]);
                pi++;
            }
    printf("pass types: %d (R<={2} chars, P in 1..2 chars)\n", pi);
    printf("search: pipelines of depth <= %d on %d battery texts\n", maxd, NB);
    for (int j = 0; j < NB; j++) strcpy(cur[j], BAT_IN[j]);
    clock_t t0 = clock();
    dfs(0, maxd);
    printf("nodes explored: %lld, battery-matching pipelines: %lld\n",
           nodes, found);
    printf("elapsed: %.1f s\n", (double)(clock() - t0) / CLOCKS_PER_SEC);
    return 0;
}
