use std::str::FromStr;
use crate::ast::{Tok};
grammar;

pub Expression: Vec<Tok> = {
    Tokz*,
}

Tokz: Tok = {
    Literal => Tok::Literal(<>),
    VarName => Tok::Var(<>),
}

VarName: String = {
    r"[a-z0-9_]*" => String::from_str(<>).unwrap(),
}

Literal: String = {
    r#""[^"]*""# => String::from_str(&<>[1..<>.len() - 1]).unwrap(),
    r#"`[^`]*`"# => String::from_str(&<>[1..<>.len() - 1]).unwrap()
}
